# base Docker Compose file
# use with environment-specific overrides:
#   dev: docker compose -f docker-compose.yml -f docker-compose.dev.yml up
#   prod: docker compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.postgis
    environment:
      POSTGRES_USER: ${DB__USERNAME}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    networks: [nn_network]
    healthcheck:
      test: |
        psql -U $DB__USERNAME -d $DB__NAME \
        -c "SELECT 1" > /dev/null || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.redis
    environment:
    # TODO: remove sensitive vars set as secret w/ pydantic-settings v2.12:
      REDIS__PASSWORD: ${REDIS__PASSWORD}
    restart: always
    volumes: 
      - redis_data:/data
    networks: [nn_network]
    healthcheck:
      test: |
        REDISCLI_AUTH=$REDIS__PASSWORD redis-cli SET hc ok EX 10 && \
        REDISCLI_AUTH=$REDIS__PASSWORD redis-cli GET hc | grep -q ok || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: api
    environment:
      ENV: ${ENV}
      REGIONS: ${REGIONS}
      # use __ nested env delimiter syntax for nested pydantic-settings objects
      # TODO: remove sensitive vars set as secret w/ pydantic-settings v2.12
      API__ADMIN_USERNAME: ${API__ADMIN_USERNAME}
      API__ADMIN_PASSWORD: ${API__ADMIN_PASSWORD}
      API__ADMIN_EMAIL: ${API__ADMIN_EMAIL}
      DB__HOST:  ${DB__HOST}
      DB__PORT: ${DB__PORT}
      DB__USERNAME:  ${DB__USERNAME}
      DB__PASSWORD:  ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
      REDIS__HOST: ${REDIS__HOST}
      REDIS__PORT:  ${REDIS__PORT}
      REDIS__PASSWORD: ${REDIS__PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [nn_network]
    healthcheck:
      # TODO: create a healthcheck endpoint, just using root for now
      test: ["CMD", "curl", "-f", "http://localhost:${API__PORT:-8000}/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
  
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: worker
    environment:
      ENV: ${ENV}
      REGIONS: ${REGIONS}
      DB__HOST: ${DB__HOST}
      DB__PORT: ${DB__PORT}
      DB__USERNAME: ${DB__USERNAME}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
      REDIS__HOST: ${REDIS__HOST}
      REDIS__PORT: ${REDIS__PORT}
      REDIS__PASSWORD: ${REDIS__PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks: [nn_network]
    healthcheck:
      test: ["CMD-SHELL", "celery -A workers.worker_app inspect ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: beat
    environment:
      ENV: ${ENV}
      REGIONS: ${REGIONS}
      REDIS__HOST: ${REDIS__HOST}
      REDIS__PORT: ${REDIS__PORT}
      REDIS__PASSWORD: ${REDIS__PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_healthy
    # NOTE: not really sure what the best protocol is for a healthcheck to make sure
    # a celery beat is running properly. could create task the container issues via
    # the beat, but seems overly complicated as of now. look into it later.
    restart: always
    networks: [nn_network]

  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: flower
    environment:
      ENV: ${ENV}
      REDIS__HOST: ${REDIS__HOST}
      REDIS__PORT: ${REDIS__PORT}
      REDIS__PASSWORD: ${REDIS__PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_healthy
    networks: [nn_network]

volumes:
  pg_data:
  redis_data:


networks: 
  nn_network:
    driver: bridge

# TODO: roll-out secrets with new release for pydantic-settings v.2.12!  
#
# secrets: 
#   db__username:  
#     environment: "DB__USERNAME"
#   db__password: 
#     environment: "DB__PASSWORD"
#   redis__password: 
#     environment: "REDIS__PASSWORD"
#   api__admin_username: 
#     environment: "API__ADMIN_USERNAME" 
#   api__admin_password: 
#     enviroment: "API__ADMIN_PASSWORD" 
#   api__admin_email:
#     enviroment: "API__ADMIN_EMAIL"
  


