import logging
from fastapi import status
from starlette.requests import Request
from starlette.exceptions import HTTPException as StarletteHTTPException
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError

from core.exceptions.base import NanaNaluException
from schemas.response_schema import ErrorResponse

logger = logging.getLogger(__name__)


def generic_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Exception handler used for any uncaught exceptions"""

    logger.critical(
        f"Unhandled Exception: {exc.__class__.__name__}",
        exc_info=True,
        extra={
            "path": request.url.path,
            "method": request.method,
            "exception_class": exc.__class__.__name__,
        },
    )

    response = ErrorResponse(
        message="An unexpected error occurred",
        error_code="internal_server_error",
    )

    return JSONResponse(
        content=response.model_dump(exclude_none=True),
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
    )


def validation_exception_handler(
    request: Request, exc: RequestValidationError
) -> JSONResponse:
    """Exception handler used for any request validation errors"""

    logger.warning(
        f"Validation error on {request.method} {request.url.path}",
        extra={"errors": exc.errors()},
    )
    errors = [
        {
            "field": ".".join(str(loc) for loc in error["loc"]),
            "message": error["msg"],
            "type": error["type"],
        }
        for error in exc.errors()
    ]

    response = ErrorResponse(
        message="Validation error",
        error_code="validation_error",
        details={"errors": errors},
    )

    return JSONResponse(
        content=response.model_dump(exclude_none=True),
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
    )


def http_exception_handler(request: Request, exc: StarletteHTTPException):
    """Exception handler for any internal HTTP errors generated by FastAPI"""

    logger.info(
        f"HTTP {exc.status_code} on {request.method} {request.url.path}",
        extra={"status_code": exc.status_code, "detail": exc.detail},
    )

    response = ErrorResponse(
        message=str(exc.detail), error_code=f"http_{exc.status_code}"
    )

    return JSONResponse(
        content=response.model_dump(exclude_none=True), status_code=exc.status_code
    )


def nana_nalu_exception_handler(
    request: Request, exc: NanaNaluException
) -> JSONResponse:
    """Exception handler used for NanaNaluExceptions"""

    status_code = getattr(exc, "status_code", status.HTTP_500_INTERNAL_SERVER_ERROR)
    log_level = logging.WARNING

    # routine client errors that don't require investigation
    client_errors = [
        status.HTTP_400_BAD_REQUEST,  # malformed request
        status.HTTP_401_UNAUTHORIZED,  # invalid credentials (failed login, maybe bad if repeated)
        status.HTTP_404_NOT_FOUND,  # resource doesn't exist
        status.HTTP_422_UNPROCESSABLE_ENTITY,  # valid request, invalid business logic
    ]

    if status_code in client_errors:
        log_level = logging.INFO
    elif status_code >= status.HTTP_500_INTERNAL_SERVER_ERROR:
        log_level = logging.ERROR

    # Build base log context
    log_extra = {
        "path": request.url.path,
        "method": request.method,
        "exception_class": exc.__class__.__name__,
        "error_code": exc.error_code,
        "status_code": exc.status_code,
    }

    # Log IP and details only for security-related events
    security_codes = [status.HTTP_403_FORBIDDEN, status.HTTP_401_UNAUTHORIZED]
    if status_code in security_codes:
        log_extra["client_ip"] = request.client.host if request.client else "unknown"
        if exc.details:
            log_extra["security_details"] = exc.details

    log_message = f"{exc.__class__.__name__}: {exc.message}"
    logger.log(
        log_level,
        log_message,
        exc_info=status_code >= status.HTTP_500_INTERNAL_SERVER_ERROR,
        extra=log_extra,
    )

    # don't expose internal security details to client for 403 errors
    response_details = None if status_code == status.HTTP_403_FORBIDDEN else exc.details

    response = ErrorResponse(
        message=exc.message,
        error_code=exc.error_code,
        details=response_details,
    )

    return JSONResponse(
        content=response.model_dump(exclude_none=True), status_code=status_code
    )
