[project]
name = "nn-api"
version = "0.1.0"
description = "The API for handling most if not all of the backend logic for the NN project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.1",
    "fastapi[standard]>=0.115.12",
    "geoalchemy2>=0.17.1",
    "pydantic-settings>=2.9.1",
]
