"""init timescaledb schema

Revision ID: 3453bf8a0e04
Revises:
Create Date: 2026-04-21 12:05:43.447878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3453bf8a0e04"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=20), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("run_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingest_status",
            sa.Enum("COMPLETED", "FAILED", "SKIPPED", name="ingeststatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "model", "region", "run_time", name="uq_model_run_id"
        ),
    )
    op.create_geospatial_table(
        "forecast_data",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("valid_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "loc",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("model_run_id", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_runs.id"],
        ),
    )
    op.create_geospatial_index(
        "ix_forecast_data_loc",
        "forecast_data",
        ["loc"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###

    # ### start of custom written commands ###
    # https://www.tigerdata.com/docs/reference/timescaledb/hypertables/create_hypertable
    op.execute("SELECT create_hypertable('forecast_data', by_range('valid_time'))")
    op.execute("SELECT add_rentention_policy('forecast_data', INTERVAL '14 days')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "ix_forecast_data_loc",
        table_name="forecast_data",
        postgresql_using="gist",
        column_name="loc",
    )
    op.drop_geospatial_table("forecast_data")
    op.drop_table("model_runs")
    # ### end Alembic commands ###
