"""init timescaledb schema

Revision ID: 36ac89e70653
Revises:
Create Date: 2026-05-12 16:02:49.991106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "36ac89e70653"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=20), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("lat_origin", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("lon_origin", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("lat_res", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("lon_res", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("lat_count", sa.Integer(), nullable=False),
        sa.Column("lon_count", sa.Integer(), nullable=False),
        sa.Column("horizon_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "model", "region", "run_time", name="uq_model_run_id"
        ),
    )
    op.create_table(
        "forecast_data",
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("valid_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lat", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("lon", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("model_run_id", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_run_id"], ["model_runs.id"], ondelete="CASCADE"
        ),
    )
    op.create_index(
        "ix_forecast_data_lookup",
        "forecast_data",
        ["model_run_id", "lat", "lon", "valid_time"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute(
        "SELECT create_hypertable('forecast_data', by_range('valid_time'), if_not_exists => TRUE)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_forecast_data_lookup", table_name="forecast_data")
    op.drop_table("forecast_data")
    op.drop_table("model_runs")
    # ### end Alembic commands ###
