"""Initial Migration

Revision ID: 8d6d0b07b906
Revises: 
Create Date: 2025-12-31 10:42:07.221508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '8d6d0b07b906'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_geospatial_table('surf_spots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_surf_spots_location', 'surf_spots', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('spot_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('observation_time', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('wave_height_observed', sa.Float(), nullable=True),
    sa.Column('wind_condition_observed', sa.Enum('ON_SHORE', 'OFF_SHORE', 'NONE', name='wind_condition_observed_enum'), nullable=True),
    sa.Column('tide_height_observed', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='tide_height_observed_enum'), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surfline_spots',
    sa.Column('surfline_id', sa.String(length=24), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['surf_spots.id'], ),
    sa.PrimaryKeyConstraint('surfline_id', 'spot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surfline_spots')
    op.drop_table('spot_observations')
    op.drop_geospatial_index('idx_surf_spots_location', table_name='surf_spots', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('surf_spots')
    op.drop_table('users')
    # ### end Alembic commands ###
