from services.forecast.nomads_config import NOMADS_CONFIG_REGISTRY
from services.forecast.pacioos_config import PACIOOS_CONFIG_REGISTRY

provider_config_registries = [NOMADS_CONFIG_REGISTRY, PACIOOS_CONFIG_REGISTRY]
